# Generated by Django 3.1.7 on 2021-04-27 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paises',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=180)),
                ('nombre', models.CharField(max_length=180)),
                ('abreviatura', models.CharField(max_length=80)),
                ('estado', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_modificacion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ciudades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=180)),
                ('nombre', models.CharField(max_length=180)),
                ('abreviatura', models.CharField(max_length=80)),
                ('estado', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_modificacion', models.DateTimeField()),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admiafiliados.paises')),
            ],
        ),
        migrations.CreateModel(
            name='afiliados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=180)),
                ('apellidos', models.CharField(max_length=180)),
                ('movil', models.IntegerField()),
                ('direccion', models.CharField(max_length=280)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('estado', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_modificacion', models.DateTimeField()),
                ('id_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admiafiliados.ciudades')),
            ],
        ),
    ]
